name: push changes to main branch

on: 
  push:
    banches: 
      - main

jobs: 
  action-pull-request:
    runs-on: ubuntu-latest 
    steps: 
      - name: checkout changes
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: merge changes into main
        if: startsWith(github.ref, 'refs/heads/main')
        uses: devops-infra/action-pull-request@v0.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITTOKEN }}
        with:
          github_token: ${{ secrets.GITTOKEN }}
          title: Automatic pull request
          git_diff: true             
